const sampleData = {
    comics: [
      {
        name: 'Batman: The Killing Joke',
        slug: 'batman-the-killing-joke',
        category: "Graphic Novels",
        description: 'A dark and gripping Joker origin story by Alan Moore.',
        images: [
          '/images/sample-comics/batman-killing-joke-1.jpg',
          '/images/sample-comics/batman-killing-joke-2.jpg',
        ],
        price: 14.99,
        brand: 'DC Comics',
        rating: 4.8,
        numReviews: 120,
        stock: 15,
        isFeatured: true,
        banner: 'banner-batman.jpg',
      },
      {
        name: 'Spider-Man: Kraven’s Last Hunt',
        slug: 'spider-man-kravens-last-hunt',
        category: "Graphic Novels",
        description: 'One of the greatest Spider-Man stories ever told.',
        images: [
          '/images/sample-comics/spider-man-kraven-1.jpg',
          '/images/sample-comics/spider-man-kraven-2.jpg',
        ],
        price: 17.99,
        brand: 'Marvel Comics',
        rating: 4.7,
        numReviews: 85,
        stock: 10,
        isFeatured: true,
        banner: 'banner-spiderman.jpg',
      },
      {
        name: 'X-Men: Dark Phoenix Saga',
        slug: 'x-men-dark-phoenix-saga',
        category: "Graphic Novels",
        description: 'The legendary X-Men storyline that changed everything.',
        images: [
          '/images/sample-comics/xmen-dark-phoenix-1.jpg',
          '/images/sample-comics/xmen-dark-phoenix-2.jpg',
        ],
        price: 19.99,
        brand: 'Marvel Comics',
        rating: 4.9,
        numReviews: 95,
        stock: 8,
        isFeatured: false,
        banner: null,
      },
      {
        name: 'Superman: Red Son',
        slug: 'superman-red-son',
        category: "Graphic Novels",
        description: 'An alternate universe tale where Superman lands in the USSR.',
        images: [
          '/images/sample-comics/superman-red-son-1.jpg',
          '/images/sample-comics/superman-red-son-2.jpg',
        ],
        price: 16.99,
        brand: 'DC Comics',
        rating: 4.6,
        numReviews: 78,
        stock: 12,
        isFeatured: false,
        banner: null,
      },
      {
        name: 'The Infinity Gauntlet',
        slug: 'the-infinity-gauntlet',
        category: "Graphic Novels",
        description: 'Thanos wields ultimate power in this cosmic Marvel epic.',
        images: [
          '/images/sample-comics/infinity-gauntlet-1.jpg',
          '/images/sample-comics/infinity-gauntlet-2.jpg',
        ],
        price: 24.99,
        brand: 'Marvel Comics',
        rating: 4.8,
        numReviews: 130,
        stock: 5,
        isFeatured: false,
        banner: null,
      },
      {
        name: 'Watchmen',
        slug: 'watchmen',
        category: "Graphic Novels",
        description: "Alan Moore’s groundbreaking deconstruction of superheroes.",
        images: [
          '/images/sample-comics/watchmen-1.jpg',
          '/images/sample-comics/watchmen-2.jpg',
        ],
        price: 22.99,
        brand: 'DC Comics',
        rating: 4.9,
        numReviews: 200,
        stock: 7,
        isFeatured: true,
        banner: null,
      },
    ],
  };

  export default sampleData;
